# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
 - role: control-plane
   kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
   extraPortMappings:
      - containerPort: 3006
        hostPort: 3006
        protocol: TCP
      # - containerPort: 443
      #   hostPort: 443
      #   protocol: TCP

 - role: worker
 - role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.tjonahen.home:5000"]
    endpoint = ["http://registry.tjonahen.home:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.tjonahen.home:5000".tls]
    insecure_skip_verify = true


