version: "3.5"
services:
  sonarqube:
    image: "sonarqube:lts"
    ports:
     - "9000:9000"
    links:
     - sonarqubedb
    environment:
     - sonar.jdbc.username=sonar
     - sonar.jdbc.password=sonar
     - sonar.jdbc.url=jdbc:postgresql://sonarqubedb:5432/sonar
    volumes:
     - '$SRV_HOME/sonarqube/extentions:/opt/sonarqube/extentions'
     - '$SRV_HOME/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins'
    networks:
     default:
       aliases:
         - sonar.tjonahen.home

  sonarqubedb:
    image: postgres:latest
    volumes:
      - '$SRV_HOME/sonarqubedb:/var/lib/postgresql'
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
     - POSTGRES_DB=sonar



networks:
  default:
    external:
       name: local-sb-network
