version: "3.5"
services:
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    ports:
      - 3009:3000
    volumes:
      - ./data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - 3010:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml

networks:
  default:
    external:
      name: local-sb-network
