version: "3.5"
services:
  web:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: gitlab
    domainname: tjonahen.home
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.tjonahen.home:3080'
        gitlab_rails['gitlab_shell_ssh_port'] = 3022
    ports:
      - '3080:3080'
      - '3022:22'
    volumes:
      - '$SRV_HOME/gitlab/config:/etc/gitlab'
      - '$SRV_HOME/gitlab/logs:/var/log/gitlab'
      - '$SRV_HOME/gitlab/data:/var/opt/gitlab'
    networks:
      default:
        aliases:
         - gitlab.tjonahen.home

networks:
  default:
    external:
       name: local-sb-network

