
version: "3.5"
services:
  nginx-proxy:
    image: nginx:alpine
    volumes:
     - ./nginx/cache:/var/cache/nginx
     - ./nginx/pid:/var/run
     - ./nginx/conf:/etc/nginx
     - ./nginx/content:/usr/share/nginx/html:ro
    network_mode: host
