
version: "3.5"
services:
  nginx-proxy:
    image: nginx:alpine
    volumes:
     - ./nginx/cache:/var/cache/nginx
     - ./nginx/pid:/var/run
     - ./nginx/conf:/etc/nginx
     - ./nginx/content:/usr/share/nginx/html:ro
    ports:
     - "80:80"
    environment:
     - NGINX_ENTRYPOINT_QUIET_LOGS=1
    network_mode: host
