
version: "3.5"
web:
  image: nginx:alpine
  volumes:
   - ./nginx/cache:/var/cache/nginx
   - ./nginx/pid:/var/run
   - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
   - ./nginx/content:/usr/share/nginx/html:ro
  ports:
   - "80:80"
  environment:
   - NGINX_ENTRYPOINT_QUIET_LOGS=1
