version: "3.5"
services:
  portainer:
    image:  portainer/portainer-ce
    restart: unless-stopped
    ports:
     - 9001:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data

volumes:
  portainer_data:
