jenkins:
  image: "jenkins-ptj"
  ports:
   - "8081:8080"
   - "50000:50000"
  links:
   - sonarqube:sonarqube.tjonahen.nl
  volumes_from:
   - jenkinsdata

jenkinsdata:
  image: "jenkins"
  volumes:
    - /var/jenkins_home
    - /home/ordina/.m2:/var/jenkins_home/.m2
    - /home/ordina:/home/ordina
  command: /bin/true

sonarqube:
  image: "sonarqube:5.4"
  ports:
   - "9000:9000"
  links:
   - db
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  volumes_from:
   - plugins

db:
  image: postgres:9.1
  volumes_from:
    - datadb
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar

datadb:
  image: postgres:9.1
  volumes:
    - /var/lib/postgresql
  command: /bin/true

plugins:
  image: "sonarqube:5.4"
  volumes:
   - /opt/sonarqube/extensions
   - /opt/sonarqube/lib/bundled-plugins
  command: /bin/true

mongodb:
  image: mongo:latest
  container_name: mongodb
  command: mongod --smallfiles
  ports:
   - "27017:27017"
  volumes:
   - ./mongo:/data/db:rw
  volume_driver: local

hygieia-api:
  image: capitalone/hygieia-api:latest
  container_name: hygieia-api
  ports:
  - "8082:8080"
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo

hygieia-ui:
  image: capitalone/hygieia-ui:latest
  container_name: hygieia-ui
  ports:
  - "8088:80"
  links:
  - hygieia-api
  
hygieia-github-scm-collector:
  image: capitalone/hygieia-github-scm-collector:latest
  container_name: hygieia-github
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
# place any values you want to change in docker-compose.override.yml
#  environment:
#  - GITHUB_HOST=github.com
#  - GITHUB_CRON='0 0/5 * * * *'
#  - GITHUB_COMMIT_THREASHOLD_DAYS=15  
  
hygieia-jenkins-build-collector:
  image: capitalone/hygieia-jenkins-build-collector:latest
  container_name: hygieia-jenkins-build
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  - jenkins
  environment:
#Jenkins server (required) - Can provide multiple
  - JENKINS_MASTER=http://jenkins:8080
#If using username/token for api authentication (required for Cloudbees Jenkins Ops Center) see sample
#  - JENKINS_OP_CENTER=http://username:token@jenkins.company.com
#Another option: If using same username/password Jenkins auth - set username/apiKey to use HTTP Basic Auth (blank=no auth)
#  - JENKINS_USERNAME
#  - JENKINS_API_KEY
#  - JENKINS_CRON=0 0/5 * * * *
#Determines if build console log is collected - defaults to false
#  - JENKINS_SAVE_LOG=true

hygieia-sonar-codequality-collector:
  image: capitalone/hygieia-sonar-codequality-collector:latest
  container_name: hygieia-sonar-codequality
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
  - hygieia-api
  - sonarqube:sonarqube.tjonahen.nl
  environment:
#  - SONAR_CRON=0 0/5 * * * *
  - SONAR_URL=http://sonarqube.tjonahen.nl:9000  