version: "3.5"
services:

  configserver:
    image: localhost:5000/tjonahen/configserver
    environment:
      - PROGRAM_OPTS=-Xlog:gc*:file=/logs/config-gc.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - LOGGING_FILE=/logs/application-config.log
    ports:
      - "8888:80"
      - "9999:9090"
    volumes:
      - /home/philippe/base/config:/config-repo
      - vlogs:/logs
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  eurekaserver:
    image: localhost:5000/tjonahen/eurekaserver
    environment:
      - PROGRAM_OPTS=-Xlog:gc*:file=/logs/eureka-gc.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - LOGGING_FILE=/logs/application-eureka.log
    ports:
      - "8761:80"
      - "9761:9090"
    volumes:
      - vlogs:/logs
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped

  zipkinserver:
    image: localhost:5000/tjonahen/zipkinserver
    environment:
      - PROGRAM_OPTS=-Xlog:gc*:file=/logs/eureka-gc.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - LOGGING_FILE=/logs/application-zipkin.log
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver/eureka/
    ports:
      - "9411:9411"
      - "9762:9090"
    volumes:
      - vlogs:/logs
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped


volumes:
  vlogs:

networks:
  default:
    external:
      name: local-sb-network
