swagger:
  image: tjonahen/swagger
  ports:
  - "8087:80"
  
abk-httpd:
  image: tjonahen/abk-httpd:latest
  ports:
  - "8888:80"
  links:
  - abk-user
  - abk-admin
  - abk-accounts
  - abk-costcenters
  - abk-transactions
  - abk-upload
  - abk-client
  
abk-client:
  image: tjonahen/abk-client:latest
  ports:
  - "8088:80"

abk-admin:
  image: tjonahen/abk-admin:latest
  ports:
   - "3000:80"
  links:
   - derbydb
  environment:
   - DATABASE_UNIT=abk
   - DATABASE_URL=jdbc:derby://derbydb:1527/abk

abk-accounts:
  image: tjonahen/abk-accounts:latest
  ports:
   - "3001:80"
  links:
   - derbydb
  environment:
   - DATABASE_UNIT=abk
   - DATABASE_URL=jdbc:derby://derbydb:1527/abk

abk-costcenters:
  image: tjonahen/abk-costcenters:latest
  ports:
   - "3002:80"
  links:
   - derbydb
  environment:
   - DATABASE_UNIT=abk
   - DATABASE_URL=jdbc:derby://derbydb:1527/abk

abk-transactions:
  image: tjonahen/abk-transactions:latest
  ports:
   - "3003:80"
  links:
   - derbydb
  environment:
   - DATABASE_UNIT=abk
   - DATABASE_URL=jdbc:derby://derbydb:1527/abk

abk-upload:
  image: tjonahen/abk-upload:latest
  ports:
   - "3004:80"
  links:
   - derbydb
  environment:
   - DATABASE_UNIT=abk
   - DATABASE_URL=jdbc:derby://derbydb:1527/abk

abk-user:
  image: tjonahen/abk-user:latest
  ports:
   - "3005:80"
  links:
   - derbydb
  environment:
   - DATABASE_UNIT=abk
   - DATABASE_URL=jdbc:derby://derbydb:1527/abk

derbydb:
  image: tjonahen/derbydb:latest
  ports:
  - "1527:1527"
  volumes:
    - ./abk-data:/dbs

