gogs:
  image: gogs/gogs:0.11.91
  ports:
  - 10080:3000
  links:
  - dbgogs
  volumes:
  - gogs_data:/data


dbgogs:
  image: postgres:11.5
  volumes:
    - postgresql_data:/var/lib/postgresql
  environment:
   - POSTGRES_USER=gogs
   - POSTGRES_PASSWORD=gogs

