version: "3.5"
services:
  derbydb:
    image: localhost:5000/tjonahen/abk-derbydb:latest
    restart: unless-stopped
    ports:
      - 1521:1521
    environment:
      - SERVER_PORT=1521
    volumes:
      - ./abk-data:/dbs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  abk-accounts:
    image: localhost:5000/tjonahen/abk2-accounts:latest
    restart: unless-stopped
    ports:
      - 3001:3001
#      - 9191:9090
    links:
      - derbydb
    environment:
#      - PROGRAM_OPTS=-Xlog:gc*:file=/logs/abk-accounts-gc.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - spring.application.name=abk-accounts
      - spring.jpa.generate-ddl=false
      - spring.jpa.hibernate.ddl-auto=none
      - spring.datasource.url=jdbc:derby://derbydb:1521/abk
      - spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver
      - spring.datasource.username=abk
      - spring.datasource.password=abk
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver/eureka/
      - spring.sleuth.sampler.percentage=1.0
      - spring.zipkin.baseUrl=http://zipkinserver:9411/
      - spring.zipkin.sender.type=web
      - server.port=3001
      - logging.file.name=/logs/abk-accounts.log
    volumes:
      - ./logs:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  abk-costcenters:
    image: localhost:5000/tjonahen/abk2-costcenters:latest
    restart: unless-stopped
    ports:
      - 3002:3002
#      - 9192:9090
    links:
      - derbydb
    environment:
#      - PROGRAM_OPTS=-Xlog:gc*:file=/logs/abk-costcenters-gc.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - spring.application.name=abk-costcenters
      - spring.jpa.generate-ddl=false
      - spring.jpa.hibernate.ddl-auto=none
      - spring.datasource.url=jdbc:derby://derbydb:1521/abk
      - spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver
      - spring.datasource.username=abk
      - spring.datasource.password=abk
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver/eureka/
      - spring.sleuth.sampler.percentage=1.0
      - spring.zipkin.baseUrl=http://zipkinserver:9411/
      - spring.zipkin.sender.type=web
      - server.port=3002
      - logging.file.name=/logs/abk-costcenters.log
    volumes:
      - ./logs:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  abk-transactions:
    image: localhost:5000/tjonahen/abk2-transacties:latest
    restart: unless-stopped
    ports:
      - 3003:3003
#      - 9193:9090
    links:
      - derbydb
    environment:
#      - PROGRAM_OPTS=-Xlog:gc*:file=/logs/abk-transacties-gc.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - spring.application.name=abk-transactions
      - spring.jpa.generate-ddl=false
      - spring.jpa.hibernate.ddl-auto=none
      - spring.datasource.url=jdbc:derby://derbydb:1521/abk
      - spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver
      - spring.datasource.username=abk
      - spring.datasource.password=abk
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver/eureka/
      - spring.sleuth.sampler.percentage=1.0
      - spring.zipkin.baseUrl=http://zipkinserver:9411/
      - spring.zipkin.sender.type=web
      - server.port=3003
      - hibernate.generate_statistics=true
      - logging.file.name=/logs/abk-transacties.log
    volumes:
      - ./logs:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  abk-upload:
    image: localhost:5000/tjonahen/abk2-upload:latest
    restart: unless-stopped
    ports:
      - 3004:3004
#      - 9194:9090
    links:
      - abk-accounts
      - abk-transactions
    environment:
#      - PROGRAM_OPTS=-Xlog:gc*:file=/logs/abk-upload-gc.log -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
      - spring.application.name=abk-upload
      - upload.rekening_url=http://ABK-ACCOUNTS:3001/accounts
      - upload.transactions_url=http://ABK-TRANSACTIONS:3003/transactions
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver/eureka/
      - spring.sleuth.sampler.percentage=1.0
      - spring.zipkin.baseUrl=http://zipkinserver:9411/
      - spring.zipkin.sender.type=web
      - server.port=3004
      - logging.file.name=/logs/abk-upload.log
    volumes:
      - ./logs:/logs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  abk-client:
    image: localhost:5000/tjonahen/abk2-client:latest
    ports:
      - 3006:80
    links:
      - "abk-upload:upload.abk.tjonahen.home"
      - "abk-transactions:transacties.abk.tjonahen.home"
      - "abk-costcenters:costcenters.abk.tjonahen.home"
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    volumes:
      - ./nginx-cache:/var/cache/nginx
      - ./nginx-pid:/var/run

volumes:
  vlogs:

networks:
  default:
    external:
      name: local-sb-network
